# Generated by Django 3.2.18 on 2023-05-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review Title', max_length=200, unique=True),
        ),
    ]
