# Generated by Django 3.2.18 on 2023-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('awful', 'awful'), ('bad', 'bad'), ('ok', 'ok'), ('good', 'good'), ('excellent', 'excellent')], default='ok', max_length=20),
        ),
    ]
